/**
 * Phase 2 — Reinforcement: train on a persisted NN-vs-Random dataset with
 * turn-level TD(λ) advantages.
 *
 * This script does not simulate; data comes from the trajectory store (see
 * generateData.ts). Materialization assigns λ-return advantages over
 * turn-level TD errors (δ = V(next own-turn start) − V(own-turn start), the
 * final interval bootstraps to the terminal outcome: win=1, loss=0, draw=1/3)
 * and keeps POSITIVE advantage weights only (negative weights collapse the
 * policy, see SelfPlay.recordsToSamples; ε-explored actions carry only value
 * labels).
 *
 * Loads the Phase 1 model as starting point, trains once, then gates: an
 * 81-game eval against the unified cached phase1 baseline (same reference for
 * every run); the trained model is kept only if strictly better (wins, then
 * average win turn). Output: training/model/phase2/
 *
 * Usage: npx tsx training/scripts/trainPhase2.ts <dataset>
 *   <dataset>: a vs-random dataset generated from the current phase1 model
 * Env: EPOCHS (default 4), ALLOW_STALE=1 skips the dataset↔model md5 check
 */
import {setupBackend} from "../src/setupBackend";
import * as fs from "fs";
import * as path from "path";
import {datasetPath, readManifest, listDatasets, materializeCached} from "../src/TrajectoryStore";
import {
  MODEL_DIR_PHASE1, MODEL_DIR_PHASE2, DATA_DIR, BASELINE_GAMES,
  initLog, log,
  trainWithPython, testNNvsRandom, copyModelDir, weightsMd5, baselineEval,
} from "../src/trainUtils";

// ─── Config ───

const EPOCHS = Number(process.env.EPOCHS ?? "4");
// Gate evals run the full 81 games against the unified cached baseline
// (trainUtils.baselineEval): one shared reference per base model instead of a
// fresh noisy 27-game read per run (the same model read 21W to 27W at 27
// games). At 81 games the win-count σ is about 2 to 3, so only a drop beyond 5
// is labeled a regression; the label is diagnostic, keep/discard is decided
// solely by "strictly better than baseline".
const REGRESSION_MARGIN = 5;
// λ-return credit, unified across phases by the 2026-07-18 paired sweep (3 λ ×
// 3 repeats per phase on shared datasets, 81-game evals vs unified baselines):
// phase 3 collapses into the draw attractor without strong terminal-truth
// propagation (means 66W/41W/71W for λ=0/0.5/0.8 vs the 80W base), while
// phase 2 is λ-insensitive within training variance (74/71/70 vs the 71W
// base). λ=0.5 underperformed BOTH endpoints; do not compromise between them.
// The dominant variance source at every λ is training-shuffle bimodality
// (good cluster vs draw-attractor cluster), not the data or λ.
const TD_LAMBDA = 0.8;
if (!Number.isFinite(EPOCHS) || EPOCHS < 1) {
  throw new Error(`Invalid EPOCHS env value: ${process.env.EPOCHS}`);
}

// ─── Main ───

async function main() {
  await setupBackend();
  initLog("phase2.log");

  const datasetName = process.argv[2];
  if (!datasetName) {
    log("Usage: npx tsx training/scripts/trainPhase2.ts <dataset>");
    log(`Available datasets: ${listDatasets().join(", ") || "(none; run generateData.ts first)"}`);
    return;
  }
  const dataDir = datasetPath(datasetName);
  const manifest = readManifest(dataDir);
  if (manifest.type !== "vs-random") {
    log(`ERROR: dataset ${datasetName} has type ${manifest.type}; phase 2 consumes vs-random datasets.`);
    return;
  }

  if (!fs.existsSync(path.join(MODEL_DIR_PHASE1, "model.json"))) {
    log("ERROR: Phase 1 model not found. Run phase 1 first.");
    return;
  }
  const currentMd5 = weightsMd5(MODEL_DIR_PHASE1);
  if (manifest.model && manifest.model.weightsMd5 !== currentMd5) {
    if (process.env.ALLOW_STALE === "1") {
      log(`WARNING: dataset ${datasetName} was generated by a different ${manifest.model.name} ` +
        `(${manifest.model.weightsMd5} vs current ${currentMd5}); proceeding because ALLOW_STALE=1.`);
    } else {
      log(`ERROR: dataset ${datasetName} was generated by a different ${manifest.model.name} model ` +
        `(${manifest.model.weightsMd5} vs current ${currentMd5}). Regenerate it or set ALLOW_STALE=1.`);
      return;
    }
  }

  // A rerun overwrites the previous phase2 result; keep the last one recoverable
  if (fs.existsSync(path.join(MODEL_DIR_PHASE2, "model.json"))) {
    copyModelDir(MODEL_DIR_PHASE2, MODEL_DIR_PHASE2 + "_prev");
    log(`Backed up existing phase2 model to ${MODEL_DIR_PHASE2}_prev`);
  }
  copyModelDir(MODEL_DIR_PHASE1, MODEL_DIR_PHASE2);

  log(`\n=== Phase 2: Reinforcement (dataset ${datasetName}, λ=${TD_LAMBDA}, ${EPOCHS} epochs) ===`);
  const ds = manifest.stats;
  log(`Dataset: ${ds.games} games, W/L/D ${ds.wins}/${ds.losses}/${ds.draws}, avg turns ${ds.avgTurns}, simRev ${manifest.simRev}`);

  log("\nBaseline (Phase 1 model, unified):");
  const baseline = await baselineEval(MODEL_DIR_PHASE1);

  if (!fs.existsSync(DATA_DIR)) fs.mkdirSync(DATA_DIR, {recursive: true});
  const dataFile = path.join(DATA_DIR, "phase2.bin");
  const t0 = Date.now();
  const {stats: m, cached} = materializeCached(dataDir, dataFile, TD_LAMBDA);
  log(`\n${cached ? "Reusing materialized" : "Materialized"} ${m.kept}/${m.raw} samples (w > 0) in ${((Date.now() - t0) / 1000).toFixed(0)}s; ` +
    `raw turn advantages: pos ${m.posAdv} / neg ${m.negAdv} (neg discarded)`);
  if (m.kept === 0) {
    log("No meaningful samples, aborting.");
    return;
  }

  const ok = await trainWithPython(dataFile, MODEL_DIR_PHASE2, EPOCHS, m.kept, false);
  if (!ok) {
    copyModelDir(MODEL_DIR_PHASE1, MODEL_DIR_PHASE2);
    log("Training failed; phase2 restored to the phase1 starting point.");
    return;
  }
  // The gate may discard the candidate; keep it inspectable regardless
  copyModelDir(MODEL_DIR_PHASE2, MODEL_DIR_PHASE2 + "_last");

  log("\nAfter training:");
  const result = await testNNvsRandom(MODEL_DIR_PHASE2, BASELINE_GAMES);

  // Publish the trained model only if it beats the baseline (the old
  // multi-iteration loop published the best evaluation seen; single-pass
  // training keeps the same rule with baseline as the incumbent)
  if (result.wins < baseline.wins - REGRESSION_MARGIN) {
    copyModelDir(MODEL_DIR_PHASE1, MODEL_DIR_PHASE2);
    log(`VERDICT: ROLLBACK (${result.wins}W < baseline ${baseline.wins}W − ${REGRESSION_MARGIN}); phase2 restored to the starting point.`);
  } else if (result.wins > baseline.wins || (result.wins === baseline.wins && result.avgWinTurn <= baseline.avgWinTurn)) {
    log(`VERDICT: IMPROVED (${result.wins}W ${result.draws}D, avg win turn ${result.wins > 0 ? result.avgWinTurn.toFixed(1) : "-"} ` +
      `vs baseline ${baseline.wins}W/${baseline.wins > 0 ? baseline.avgWinTurn.toFixed(1) : "-"}); trained model kept.`);
  } else {
    copyModelDir(MODEL_DIR_PHASE1, MODEL_DIR_PHASE2);
    log(`VERDICT: NO-GAIN (${result.wins}W vs baseline ${baseline.wins}W, not better); phase2 restored to the starting point.`);
  }

  log("\n=== Phase 2 Done ===");
}

main().catch(console.error);
