/**
 * Phase 3 — Mixed reinforcement: train on a persisted mixed dataset
 * (opponent rotation + self-play, see generateData.ts).
 *
 * This script does not simulate. Training signal is the same as phase 2:
 * turn-level TD(λ) advantages assigned at materialization, positive weights
 * only (negative weights collapse the policy, see SelfPlay.recordsToSamples).
 *
 * Loads the Phase 2 model as starting point, trains once, then gates: an
 * 81-game eval against the unified cached phase2 baseline (same reference for
 * every run); the trained model is kept only if strictly better (wins, then
 * average win turn). Output: training/model/phase3/
 *
 * Usage: npx tsx training/scripts/trainPhase3.ts <dataset>
 *   <dataset>: a mixed dataset generated by the current phase2 model
 * Env: EPOCHS (default 4), ALLOW_STALE=1 skips the dataset↔model md5 checks
 */
import {setupBackend} from "../src/setupBackend";
import * as fs from "fs";
import * as path from "path";
import {datasetPath, readManifest, listDatasets, materializeCached} from "../src/TrajectoryStore";
import {
  MODEL_DIR_PHASE2, MODEL_DIR_PHASE3, DATA_DIR, BASELINE_GAMES,
  initLog, log,
  trainWithPython, testNNvsRandom, copyModelDir, weightsMd5, baselineEval,
} from "../src/trainUtils";

// ─── Config ───

const EPOCHS = Number(process.env.EPOCHS ?? "4");
// Gate evals run the full 81 games against the unified cached baseline
// (trainUtils.baselineEval), same instrument as phase 2. The regression label
// is diagnostic; keep/discard is decided solely by "strictly better".
const REGRESSION_MARGIN = 5;
// Mixed-outcome data needs the terminal truth propagated backward: with pure
// turn-TD (λ=0) the locally V-raising turns of drawn/lost games get reinforced
// (hoard-to-draw collapse). Unified λ fixed by the 2026-07-18 paired sweep:
// 81-game means vs the 80W base were 66W (λ=0), 41W (λ=0.5, worse than both
// endpoints), 71W (λ=0.8); λ=0.8 also held ≥75W in 2 of 3 repeats with the
// shallowest worst case. See trainPhase2.ts for the phase 2 side.
const TD_LAMBDA = 0.8;
if (!Number.isFinite(EPOCHS) || EPOCHS < 1) {
  throw new Error(`Invalid EPOCHS env value: ${process.env.EPOCHS}`);
}

// ─── Main ───

async function main() {
  await setupBackend();
  initLog("phase3.log");

  const datasetName = process.argv[2];
  if (!datasetName) {
    log("Usage: npx tsx training/scripts/trainPhase3.ts <dataset>");
    log(`Available datasets: ${listDatasets().join(", ") || "(none; run generateData.ts first)"}`);
    return;
  }
  const dataDir = datasetPath(datasetName);
  const manifest = readManifest(dataDir);
  if (manifest.type !== "mixed") {
    log(`ERROR: dataset ${datasetName} has type ${manifest.type}; phase 3 consumes mixed datasets.`);
    return;
  }

  if (!fs.existsSync(path.join(MODEL_DIR_PHASE2, "model.json"))) {
    log("ERROR: Phase 2 model not found. Run phase 2 first.");
    return;
  }

  // The dataset must have been played by the models currently on disk: the
  // generating model must be the current phase2 (it is also the baseline), and
  // NN opponents must match their current dirs
  const staleChecks: string[] = [];
  const currentPhase2 = weightsMd5(MODEL_DIR_PHASE2);
  if (manifest.model && manifest.model.weightsMd5 !== currentPhase2) {
    staleChecks.push(`generating model ${manifest.model.name} (${manifest.model.weightsMd5} vs current ${currentPhase2})`);
  }
  for (const opp of manifest.opponents) {
    if (!opp.weightsMd5) continue;
    const current = weightsMd5(path.resolve("training/model", opp.name));
    if (opp.weightsMd5 !== current) staleChecks.push(`opponent ${opp.name} (${opp.weightsMd5} vs current ${current})`);
  }
  if (staleChecks.length > 0) {
    if (process.env.ALLOW_STALE === "1") {
      log(`WARNING: dataset ${datasetName} is stale: ${staleChecks.join("; ")}; proceeding because ALLOW_STALE=1.`);
    } else {
      log(`ERROR: dataset ${datasetName} is stale: ${staleChecks.join("; ")}. Regenerate it or set ALLOW_STALE=1.`);
      return;
    }
  }

  // A rerun overwrites the previous phase3 result; keep the last one recoverable
  if (fs.existsSync(path.join(MODEL_DIR_PHASE3, "model.json"))) {
    copyModelDir(MODEL_DIR_PHASE3, MODEL_DIR_PHASE3 + "_prev");
    log(`Backed up existing phase3 model to ${MODEL_DIR_PHASE3}_prev`);
  }
  copyModelDir(MODEL_DIR_PHASE2, MODEL_DIR_PHASE3);

  log(`\n=== Phase 3: Mixed Reinforcement (dataset ${datasetName}, λ=${TD_LAMBDA}, ${EPOCHS} epochs) ===`);
  const ds = manifest.stats;
  log(`Dataset: ${ds.games} games, W/L/D ${ds.wins}/${ds.losses}/${ds.draws}, avg turns ${ds.avgTurns}, simRev ${manifest.simRev}`);

  log("\nBaseline (Phase 2 model, unified):");
  const baseline = await baselineEval(MODEL_DIR_PHASE2);

  if (!fs.existsSync(DATA_DIR)) fs.mkdirSync(DATA_DIR, {recursive: true});
  const dataFile = path.join(DATA_DIR, "phase3.bin");
  const t0 = Date.now();
  const {stats: m, cached} = materializeCached(dataDir, dataFile, TD_LAMBDA);
  log(`\n${cached ? "Reusing materialized" : "Materialized"} ${m.kept}/${m.raw} samples (w > 0) in ${((Date.now() - t0) / 1000).toFixed(0)}s; ` +
    `raw turn advantages: pos ${m.posAdv} / neg ${m.negAdv} (neg discarded)`);
  if (m.kept === 0) {
    log("No meaningful samples, aborting.");
    return;
  }

  const ok = await trainWithPython(dataFile, MODEL_DIR_PHASE3, EPOCHS, m.kept, false);
  if (!ok) {
    copyModelDir(MODEL_DIR_PHASE2, MODEL_DIR_PHASE3);
    log("Training failed; phase3 restored to the phase2 starting point.");
    return;
  }
  // The gate may discard the candidate; keep it inspectable regardless
  copyModelDir(MODEL_DIR_PHASE3, MODEL_DIR_PHASE3 + "_last");

  log("\nAfter training:");
  const result = await testNNvsRandom(MODEL_DIR_PHASE3, BASELINE_GAMES);

  if (result.wins < baseline.wins - REGRESSION_MARGIN) {
    copyModelDir(MODEL_DIR_PHASE2, MODEL_DIR_PHASE3);
    log(`VERDICT: ROLLBACK (${result.wins}W < baseline ${baseline.wins}W − ${REGRESSION_MARGIN}); phase3 restored to the phase2 starting point.`);
  } else if (result.wins > baseline.wins || (result.wins === baseline.wins && result.avgWinTurn <= baseline.avgWinTurn)) {
    log(`VERDICT: IMPROVED (${result.wins}W ${result.draws}D, avg win turn ${result.wins > 0 ? result.avgWinTurn.toFixed(1) : "-"} ` +
      `vs baseline ${baseline.wins}W/${baseline.wins > 0 ? baseline.avgWinTurn.toFixed(1) : "-"}); trained model kept.`);
  } else {
    copyModelDir(MODEL_DIR_PHASE2, MODEL_DIR_PHASE3);
    log(`VERDICT: NO-GAIN (${result.wins}W vs baseline ${baseline.wins}W, not better); phase3 restored to the phase2 starting point.`);
  }

  log("\n=== Phase 3 Done ===");
}

main().catch(console.error);
